### ISSUE TITLE
Problem installing mongo plugin on windows machine

### ISSUE THREAD

**Issue by NTTAKR** [fluent/fluent-plugin-mongo#103]
Hi!
I want to use the fluent-plugin-mongo to push events to mongodb. 
I have installed fluentd on a windows machine. It works fine.

I want to use mongo plugin => plugin is not installed. 
Website tells to use "fluent-gem install fluent-plugin-mongo" to install. 
Using this I get an error:
    'make' is not recognized as an internal or external command,
    operable program or batch file.

fluentd or rubydevkit does not include a make command. 
I installed gnuwin32 to use the make. 

I then get this error: 

    make "DESTDIR="
    generating bson_native-x64-mingw32.def
    make: *** No rule to make target `/C/opt/td-agent/embedded/include/ruby-2.4.0/ruby.h', needed by 
    `bson_native.o'.  Stop.

What can I do to install and use mongo plugin in fluentd?

Thanks
  Andreas

**Comment by repeatedly** [comment]
Maybe, it needs msys or similar environment but I'm not sure which is the best.
Asking it on mongodb forum is better.

**Comment by cosmo0920** [comment]
Another solutions is using MSYS2.

I'm using RubyInstaller2 with MSYS2 on Windows environment when I develop Fluentd and its plugins run their tests.
RubyInstaller2 is included MSYS2.
If you use ruby which is installed by RubyInstaller, you can compile native extension by `ridk` command.
https://github.com/oneclick/rubyinstaller2#the-ridk-command

**Comment by repeatedly** [comment]
To follow msys2/ridk, you need to install mingw-w64-x86_64 prefixed packages to build C extension gems.

```
pacman -S mingw-w64-x86_64-binutils mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config
```

**Comment by ramprasadpatnaik** [comment]
try gem install fluent-plugin-mongo -v 0.7.11

**Comment by cosmo0920** [comment]
With td-agent3, we cannot proceed to install fluentd plugins which need to install C extension included dependent gems.
With td-agent 4.0.1 (patched future release), it detects and handles MSYS2 installation and we can install C extension included dependent gem with `ridk exec` prefixed installation command:

```
cmd> ridk exec fluent-gem install fluent-plugin-mongo
```

This should be closing after [the task](https://github.com/fluent-plugins-nursery/td-agent-builder/issues/133) is done.

**Comment by cosmo0920** [comment]
We'd confirmed that td-agent 4.0.1 can be workable with C extension included gem such as winevt_c or bson:
```console
cmd> ridk exec td-agent-gem install fluent-plugin-mongo
```
Using td-agent 4.0.1 and MSYS2 can handle fluent-plugin-mongo and its dependent gems installation.
We can close this issue.

**Comment by Eliav2** [comment]
for anyone who encountered this as me:

run `ridk install` and then enter `1,2,3` and wait for the install to finish(takes some time).
```bash
> ridk install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [1,3] 1,2,3
......
```

then re-run `fluent-gem install fluent-plugin-mongo` .
it worked for me
