### ISSUE TITLE
Unable to authenticate on Mongo DB - 'fluent-plugin-mongo' version '0.7.15' 

### ISSUE THREAD

**Issue by nreddy67** [fluent/fluent-plugin-mongo#115]
Hi,
I am unable to authenticate against the MongoDB instance. It says - "fluent/log.rb:382:fatal: Could not authorize user admin on database admin". Pasting the match tag for your reference.

I was able to connect to the same mongo instance using Studio 3T providing the same credentials as below and authentication is happening perfectly fine.

Match:

<match mongo.**>
@type mongo
user admin
password ********
database admin
host abcd23756
port 27017
collection docker
Note: I have docker image in my local and working fine with the local mongo instance which has no credentials. But the issues arrises when authenticated against other mongo instance that needs credentials.

Error Logs:
2019-03-19 05:16:23 +0000 [info]: #0 fluent/log.rb:322:info: starting fluentd worker pid=35 ppid=6 worker=0
2019-03-19 05:16:23 +0000 [fatal]: #0 fluent/log.rb:382:fatal: Could not authorize user admin on database admin.
2019-03-19 05:16:23 +0000 [info]: fluent/log.rb:322:info: Worker 0 finished unexpectedly with status 1
2019-03-19 05:16:23 +0000 [info]: fluent/log.rb:322:info: gem 'fluent-plugin-mongo' version '0.7.15'
2019-03-19 05:16:23 +0000 [info]: fluent/log.rb:322:info: gem 'fluentd' version '1.2.4'
2019-03-19 05:16:23 +0000 [info]: fluent/log.rb:322:info: adding match pattern="mongo.**" type="mongo"
** Notice: The native BSON extension was not loaded. **

  For optimal performance, use of the BSON extension is recommended.

  To enable the extension make sure ENV['BSON_EXT_DISABLED'] is not set
  and run the following command:

    gem install bson_ext

  If you continue to receive this message after installing, make sure that
  the bson_ext gem is in your load path.

**Comment by repeatedly** [comment]
Could you paste your steps/commands for creating admin user to reproduce the issue?

**Comment by nreddy67** [comment]
I haven't explicitly used any commands to create the users. Our admin team took care of the user create tasks. And as mentioned in the previous post using admin user credentials which has read/write access on the DB, I was able to create collection, insert data with Studio 3T

**Comment by repeatedly** [comment]
Could you paste mongodb log?
If you hit authentication error, mongodb log shold generate some logs for it.

**Comment by repeatedly** [comment]
BTW, 0.7.15 version is too old version and hard to debug because it also uses outdated mongo v1 client. If you are ok, please upgrade plugin/mongo client.

**Comment by nreddy67** [comment]
Thank you very much for helping on this issue. upgraded my Mongo plugin to the newer version and it solved the issue.
