### ISSUE TITLE
Unknown output plugin 'mongo'

### ISSUE THREAD

**Issue by rameshVeeramani** [fluent/fluent-plugin-mongo#124]
Integration  of Fluentd To MongoDB stalled because of tdagent unablet to recognize the installed mongo plugin on Centos. The logs has 

``
2019-06-05 15:44:09 -0500 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2019-06-05 15:44:10 -0500 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'mongo'. Run 'gem search -rd fluent-plugin' to find plugins"
``

The td-agent.conf has 
``
<match my_mem**>
  @type mongo
  host ***
  port 27017
  database from_fluentd
  tag_mapped
  collection misc
</match>
``

and the plugin mongo is installed
``
gem list --local | grep mongo
fluent-plugin-mongo (1.3.0)
mongo (2.6.4)
 
`` 

But fluentd doesn't recognize the mongo plugin and throws up the above exception .. 

I installed mongo using
gem install fluent-plugin-mongo

Why isnt  fluentd recognizing the mongo plugin.

**Comment by repeatedly** [comment]
See https://docs.fluentd.org/deployment/plugin-management#if-using-td-agent-use-usr-sbin-td-agent-gem

**Comment by rameshVeeramani** [comment]
Thanks ; 

Was using fluent-plugin-gem to install the plugin ; 

Uninstalled the plugin and installed it using 
``
td-agent-gem install fluent-plugin-mongo
``
Was able to connect and create collection 
Thanks
