### ISSUE TITLE
Unable to activate fluent-plugin-mongo-1.3.0

### ISSUE THREAD

**Issue by s-shubh** [fluent/fluent-plugin-mongo#126]
While working with this plugin; I got this error.

/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate fluent-plugin-mongo-1.3.0, because mongo-2.9.0 conflicts with mongo (~> 2.6.0) (Gem::ConflictError)

Tried to update gems but it could not be resolved. 

Using td-agent of fluentd in Cent7.

**Comment by repeatedly** [comment]
Maybe, you install mongo 2.9.0. Please remove mongo 2.9.0. mongo 1.3.0 requires mongo 2.6.x serise.

**Comment by s-shubh** [comment]
I have uninstalled it. and my system does not have mongodb installed.

**Comment by repeatedly** [comment]
I mean mongo gem. You can use `-v` option to specify version.

`gem install mongo -v 2.6.4`

**Comment by s-shubh** [comment]
I have already uninstalled mongo 2.9.0 and installed 2.6.4 but no success. still got similar logs

**Comment by repeatedly** [comment]
Could you show me the result of `/usr/sbin/td-agent-gem list` ?

**Comment by s-shubh** [comment]
Hey, Thank you for your time.... I tried to reinstall mongo 2.6.4 and then uninstalled mongo 2.8.0. Then Issue seems resolved.

**Comment by repeatedly** [comment]
Ok. Closed.
