### ISSUE TITLE
mongo_tail: Updates in mongodb are not reflected in elastic

### ISSUE THREAD

**Issue by shbhshs** [fluent/fluent-plugin-mongo#144]
I am trying to sync mongo data to elastic, It works fine. But if I update some document in mongo, then changes are not reflected to elasticsearch. 
Is this behaviour normal, or am I missing something?

**Comment by repeatedly** [comment]
> Is this behaviour normal

Maybe normal. `in_mongo_tail` depends on capped collection behavior and capped collection seems to not update document order.

**Comment by shbhshs** [comment]
Thanks for response @repeatedly.
