### ISSUE TITLE
"journaled" write concern support

### ISSUE THREAD

**Issue by willemt** [fluent/fluent-plugin-mongo#37]
Is the "journaled" write concern option supported? (http://docs.mongodb.org/manual/reference/write-concern/#j-option). After looking at the code, it doesn't seem like it - just want to confirm please.

When looking at this line (https://github.com/fluent/fluent-plugin-mongo/blob/master/lib/fluent/plugin/out_mongo.rb#L72), shouldn't @connection_options[:w] be @connection_options[:write]? (https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/client.rb#L111)

Thanks for your time

**Comment by repeatedly** [comment]
Sorry for the delay. I just added 'journaled' option to enable journaled write.

> @connection_options[:write]?

fluent-plugin-mongo depends on mongo gem 1.x. 1.x uses `:w` so it is not the problem.

**Comment by repeatedly** [comment]
Just released v0.7.5 with this feature.

**Comment by willemt** [comment]
Thanks - this is great
