### ISSUE TITLE
I Wanna Use Mongo Driver 1.12

### ISSUE THREAD

**Issue by Shota-Tajiri** [fluent/fluent-plugin-mongo#60]
Hi, I have question.

I wanna use MondoDB 3.0, because customer hope it.

But this plug-in supports Mongo Driver 1.9.

```
@fluent-plugin-mongo.gemspec
gem.add_dependency "mongo", "~> 1.9"
```

If this plug-in supports Mongo Driver 1.12, I can use MongoDB 3.0
(It's specified in Mongo Offical Site)

Do you have any problems, even If I use this plug-in with Mongo Driver 1.12?

**Comment by repeatedly** [comment]
You can use mongo gem v1.12. `~>` is not `==`.
See rubygems document for more detail.

**Comment by Shota-Tajiri** [comment]
Thanks for you quick reply.

I know '~>' is not '=='.
but I didn't know that mean which range.

Thank you for helping me.
I'll try mongoDB 3.0 with this plug-in.
