### ISSUE TITLE
Failed to insert large amount of data in a single time

### ISSUE THREAD

**Issue by justanding** [fluent/fluent-plugin-mongo#63]
Hello.
I tried to insert large amount of data  in a single time using your plugin (actually the data is just an large array). But it didn't work. What I get is not the original data but some binary data instead. However, I successfully insert the data with the official Mongo PHP extension on my local machine. 
I have gone through your code and I assumed that it didn't work on Line 152 of your "out_mongo.rb" file.
I am just wondering how I can use your plugin successfully? Look forward to your reply. Thank you.

**Comment by repeatedly** [comment]
> What I get is not the original data but some binary data instead.

It seems this case > https://github.com/fluent/fluent-plugin-mongo#broken-data-as-a-bson

> I am just wondering how I can use your plugin successfully? 

I'm not sure because whu PHP extension can insert broken or invalid BSON data in ruby mongo driver.

**Comment by repeatedly** [comment]
No response.
