### ISSUE TITLE
Convert numbers in hash keys to strings

### ISSUE THREAD

**Issue by silentroach** [fluent/fluent-plugin-mongo#64]
Sometimes we see "keys must be strings or symbols" error in fluent logs. It is cause of numbers in hash we need to log.

It will be great to have an option to convert any numeric keys in hashes to strings to avoid problems with BSON serialization.

**Comment by repeatedly** [comment]
Please use typecast filter or record_transformer filter.
It is not mongodb output plugin's responsibility.

**Comment by silentroach** [comment]
But why dots and dollar signs are in plugin responsibility?

**Comment by repeatedly** [comment]
Because v0.10 doesn't have filter mechanizm.

**Comment by repeatedly** [comment]
I check above plugins and they don't have key convert feature.
So you should write filter plugin to convert number keys to string.

**Comment by silentroach** [comment]
ok, thank you

**Comment by repeatedly** [comment]
I'm not sure your logging environment.
Almost json based system hard to handle number keys because json's key must be string.
So I recommend to use string type for keys.
Some fluentd plugins also assume key is string.

**Comment by silentroach** [comment]
We write logs via msgpack, not via json
