### ISSUE TITLE
Upgrade Mongo Ruby driver to 2.x series

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-plugin-mongo#65]
## Problems when using Ruby Mongo Driver 2.1 series in fluent-plugin-mongo
- `collection.insert_many` does not handle invalid records
  - `writeErrors` contains only invalid ids for efficiency 
    - ref: https://jira.mongodb.org/browse/RUBY-1062?focusedCommentId=1085959&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1085959
- It cannot change current Ruby driver 2.1 behavior, it's mongo specifications. (above issue is marked won't fix) 
  - ref: https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#results
### How To Upgrade
- Insert records one by one (become slower)
- Use bulk insert and ignore writing errors
- Use bulk insert but detect writing errors by fluent-plugin-mongo side

Which upgrading strategy is better?
### Benchmarks

Sited from https://github.com/okkez/fluent-plugin-mongo/issues/1
Benchmarking code: https://gist.github.com/cosmo0920/b33c96e071c5c6923304
### With Mongo Driver 1.12.3

``` log
insert one by one (legacy)
       user     system      total        real
   2.880000   0.530000   3.410000 (  5.365804)
bulk insert (legacy)
       user     system      total        real
   0.200000   0.010000   0.210000 (  0.314387)
```
### With Mongo Driver 2.1.2

``` log
insert one by one
       user     system      total        real
   4.670000   0.860000   5.530000 (  8.229355)
bulk insert
       user     system      total        real
   0.150000   0.000000   0.150000 (  0.238776)
```

**Comment by repeatedly** [comment]
> Use bulk insert but detect writing errors by fluent-plugin-mongo side

This is better.

**Comment by cosmo0920** [comment]
Sorry for late response.

Verification of upgrading Mongo Ruby driver to 2.2 is almost done.
Here is verification fluentd plugin: https://github.com/cosmo0920/fluent-plugin-mongo2

And I noticed that there are some advantages and limitations using Mongo Ruby driver 2.2:

### Advantages

* Faster than old Ruby driver when using bulk insert
* Obtaining documents type become more Rubyish
* Treating replica set become more simple 

### Limitations

* Cannot retrieve broken records
  * new Mongo Ruby driver returns inserting success records' ids and number of succeeded inserting records
* Cannot manage MongoDB via the driver such as setting up replica set and obtaining MongoDB version
  * Cannot do plugin, which uses replica set, CI

### Current Verification plugin status

* Drop support to treat invalid records for MongoDB
* Drop support for test tools, which are placed in `test/tools`.

### Questions

* Send PR at once is acceptable? 
  * Perhaps, patches will become too huge....
* The sooner, the better?

**Comment by cosmo0920** [comment]
#70 is merged. Closing.
