### ISSUE TITLE
Can we debug Broken Data without ruby?

### ISSUE THREAD

**Issue by Nepoxx** [fluent/fluent-plugin-mongo#71]
The title says it all, can we debug broken data inserted into MongoDB without using Ruby?

**Comment by repeatedly** [comment]
Translated https://github.com/fluent/fluent-plugin-mongo#broken-data-as-a-bson code into your language.

**Comment by Nepoxx** [comment]
Fair enough.

I'd suggest using something other than Ruby's Marshalling since that is not standard. Using json->hex->BinData instead would allow deserializing directly from Mongo's shell

**Comment by Nepoxx** [comment]
For anyone encountering this, https://github.com/instore/node-marshal allows unmarshalling Ruby binary dta into JavaScript objects.

**Comment by repeatedly** [comment]
Ah, I forgot the marshal. Using json lost some type info so I use marshal to keep original data.
Fluentd works on Ruby so I use Ruby and Marshal to serialize the data.
