### ISSUE TITLE
date is always rewritten with current timestamp

### ISSUE THREAD

**Issue by sl4dy** [fluent/fluent-plugin-mongo#73]
I have following config of fluentd:

```
<source>
    type tail
    path /tmp/alog.json
    pos_file /tmp/alog.json.pos
    tag alog
    format json
  </source>
  <match *>
    type copy
    <store>
      type stdout
    </store>
    <store>
      @type mongo
      host localhost
      port 27017
      database test
      collection audit_log
      time_key eventdate
      flush_interval 10s
    </store>
  </match>
```

I parse following log file:
`{"user": "user9","message":    "Log in","domain": "customer","eventdate" : "2016-01-01T12:10:30Z"}`

However when I check mongo the record is always with the date of submission to mongo, not with the date from the logfile:

`{ "_id" : ObjectId("5745baca175ed22164000031"), "user" : "user9", "message" : "Log in", "domain" : "customer", "eventdate" : ISODate("2016-05-25T14:46:31Z") }`

**Comment by repeatedly** [comment]
This is not mongo plugin issue.
You should set time_key and time_format corretly in in_tail: http://docs.fluentd.org/articles/parser-plugin-overview#list-of-built-in-parsers

**Comment by repeatedly** [comment]
Output plugin doesn't have a responsibility for such time parsing.
