### ISSUE TITLE
Plugin inserts null values into array

### ISSUE THREAD

**Issue by ArthurasJ** [fluent/fluent-plugin-mongo#77]
This is my fluentd.conf file:

```
<source>
  @type tcp
  tag tcp.events
  format json
  port 24224
</source>

<match **>
  @type mongo
  host mongodb
  port 27017
  database logs
  collection logs
  replace_dot_in_key_with _
</match>
```

When I'm trying to insert a record such as this:

"{\"host\":\"ABC5\",\"timestamp\":\"147051740.871\",\"level\":\"1\",\"arrayName\":[\"8\", \"9\"],\"thread\":\"MessageBroker-3\",\"containerId\":\"?\""} \n"  (this is how it looks as Java string)

I always get an array with name "arrayName" and two empty (null) values in it. Maybe plugin does not support MongoDB arrays?

**Comment by repeatedly** [comment]
This is the bug of plugin.
I just released fixed version. Try v0.7.14.
