### ISSUE TITLE
Dynamic Collection Name From Record Field

### ISSUE THREAD

**Issue by denizarman** [fluent/fluent-plugin-mongo#85]
Hi,
I think it would be great to use any field of record by tag_mapped property. For example i would name my collections by AppId on my event. 
There are some plugins which allow me to rename tag but, those plugins doesn't seem to allow ruby capabilities and i couldn't parse record like, record["AppId"]. 
Writing Hard-Coded tag name wouldn't help me, cause new applications added to system daily. 
Is this an issue, or could you direct me any other approach?
Any help will be appreciated.

**Comment by watnotte** [comment]
I would love to see an answer to this.  Been searching around and haven't really found anything that works yet.  We have a multi-tenant setup and would like the logging routed to different MongDB database + collection depending on information in the record.  Is there a way to query the record and set the database/collection using embedded Ruby expressions?  Environment variables?  Anything else?

**Comment by watnotte** [comment]
I looked at the source for the MongoDB plugin.  Doesn't look like the docs are quite up to date but the plugin does allow you to specify:

`collection ${tag}`

However you can't do the same with the database and you can't use tag_parts.  Ideally what I'd like to do is something along the lines of:

```
database ${tag_parts[0]}
collection ${tag_parts[1]}
```

Or even better, just use the record data itself as noted in the original comment:

```
database ${record["meta.accountName"]}
collection ${record["meta.subAccountName"]}
```

**Comment by mineyang** [comment]
I also hope to have this：

> database ${tag_parts[0]}
>collection ${tag_parts[1]}
Or:
>database ${record["meta.accountName"]}
>collection ${record["meta.subAccountName"]}

**Comment by repeatedly** [comment]
We can do it with fluentd v0.14 and v1.0.0.rc seriese: http://docs.fluentd.org/v0.14/articles/buffer-section
We don't have a plan to add same feature to v0.x mongo plugin versions.

**Comment by cosmo0920** [comment]
We can already do it with fluent-plugin-mongo v1.0.0 or later and Fluentd v0.14 or later.
Does anyone also want this feature for database name?

**Comment by mineyang** [comment]
yes
