### ISSUE TITLE
Replica connection

### ISSUE THREAD

**Issue by megamk** [fluent/fluent-plugin-mongo#88]
When I'm starting fluent with `mongo_replset` type, it gives me an error:
```
config error file="fluent.conf" error_class=Fluent::ConfigError error="'replica_set' parameter is required"
```

It's clear from the source that `nodes` param was replaced by `replica_set` parameter and relies on `host` and `port` params inherited from `out_mongo` but it is not clear from the documentation.

Another question I have is what should I give as a host/port values if I have more than 1 replica member and I can't be sure that all nodes will be available in this replica  all the time?

**Comment by repeatedly** [comment]
> It's clear from the source that nodes param was replaced by replica_set parameter and relies on host and port params inherited from out_mongo but it is not clear from the documentation.

Ah, README is outdated.
We migrated old ruby driver into new one recently and we forgot to update its parameters.

> a host/port values if I have more than 1 replica member

One idea is re-add nodes parameter to out_mongo_replset.

**Comment by megamk** [comment]
> One idea is re-add nodes parameter to out_mongo_replset.

Another good alternative is to add a `connection_string parameter` so that connection type will be set up just with one parameter, since connection string supports both single host and replica with any number of nodes

**Comment by megamk** [comment]
@repeatedly I have some changes in my fork, do I need to make tests or you accept PRs without tests? 
https://github.com/megamk/fluent-plugin-mongo/commit/a8971d666d93e96c45c5c02629de2a84983a13d7

**Comment by repeatedly** [comment]
> you accept PRs without tests?

This is hard because we can't guarantee your change breaks existing behaviour.
Please add test and send a PR.
Your patch is tested on travis-ci with actual mongodb.

**Comment by repeatedly** [comment]
Release v0.8.1 with connection_string. Thanks for the idea!
