### ISSUE TITLE
Capped collection not created

### ISSUE THREAD

**Issue by ceecko** [fluent/fluent-plugin-mongo#90]
When using v0.8.0 the capped collection config is not applied.
Here's the config we use:

```
  <match docker.*>
    type mongo_replset
    tag_mapped
    remove_tag_prefix docker.
    flush_interval 10s
    max_retry_wait 60s
    host myhost.example.com
    replica_set rs0
    user logs
    password xxx
    database logs
    capped
    capped_size 2097152
  </match>
```

The resulting collection is not capped.

**Comment by aferreira** [comment]
I think that broke with the commit https://github.com/fluent/fluent-plugin-mongo/commit/d89267652f6d417e906e818ee7139f3ebba3d3f9 – for the transition to the new MongoDB driver, it was assumed that

```
@client[collection, @collection_options].insert_many(records)
```

would create the collection implicitly by applying `@collection_options` but that is not what happens.

**Comment by cosmo0920** [comment]
Could you send your patch into this repository, @aferreira ?

**Comment by cosmo0920** [comment]
Ah, it is already sent here.
I'll check it.

**Comment by repeatedly** [comment]
Merged patch.
