### ISSUE TITLE
error="Unknown output plugin 'mongo'."

### ISSUE THREAD

**Issue by elinshu** [fluent/fluent-plugin-mongo#97]
OS : windows 10
version : td-agent-3.0.1

command
> fluentd -c C:/opt/td-agent/etc/td-agent/td-agent.conf
```
error : error_class=Fluent::ConfigError error="Unknown output plugin 'mongo'. Run 'gem search -rd fluent-plugin' to find plugins"

```

command
> fluent-gem install fluent-plugin-mongo
```
C:\opt\td-agent\embedded\bin>fluent-gem install fluent-plugin-mongo
WARN: Unresolved specs during Gem::Specification.reset:
      msgpack (< 2.0.0, >= 0.7.0)
      serverengine (< 3.0.0, >= 2.0.4)
      tzinfo (~> 1.0)
      tzinfo-data (~> 1.0)
      ffi (>= 0)
      win32-api (>= 1.4.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-mongo:
        ERROR: Failed to build gem native extension.

    current directory: C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/bson-4.
3.0/ext/bson
C:/opt/td-agent/embedded/bin/ruby.exe -r ./siteconf20180405-4432-lg8nfr.rb extco
nf.rb
creating Makefile

current directory: C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/bson-4.3.0/
ext/bson
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/bson-4.3.0/
ext/bson
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/
gems/bson-4.3.0 for inspection.
Results logged to C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/extensions/x64-mi
ngw32/2.3.0/bson-4.3.0/gem_make.out

C:\opt\td-agent\embedded\bin>
```

I installed devkit(rubyinstaller-devkit-2.4.4) for this, but still not working

**Comment by repeatedly** [comment]
> 'make' is not recognized as an internal or external command,

you need to set PATH correctly. build script can't find make and other command.

**Comment by elinshu** [comment]
Actually I solved this problem 'gem install fluent-plugin-mongo -v 0.7.10' but not perfectly.
thank you

**Comment by jack2ngon** [comment]
I have same issue but on ubuntu environment. 
https://github.com/fluent/fluent-plugin-mongo/issues/104#issue-370060091

**Comment by cosmo0920** [comment]
> I already set environment variables PATH, but the same problem occurred.

This should be occurred by "make command is not found" and mongo plugin installation failure.
Ruby install with devkit does not add toolchain folder into PATH.
ref: https://github.com/oneclick/rubyinstaller2/wiki/The-ridk-tool#ridk-exec-
ref: https://github.com/oneclick/rubyinstaller2/wiki/The-ridk-tool#ridk-enable--disable

Instead, you should use `ridk exec [COMMAND]` or `ridk enable` for adding toolchain folder into PATH:

```console
cmd> ridk exec fluent-gem install fluent-plugin-mongo
```

Or,

```console
cmd> ridk enable
cmd> fluent-gem install fluent-plugin-mongo
```

This will resolve your mongo plugin installation failure.
