### ISSUE TITLE
Can't save time field with sub-second

### ISSUE THREAD

**Issue by tmurakam** [fluent/fluent-plugin-mongo#98]
I can't save time field with sub-seconds (milliseconds).

I found that the MongoOutput.format() method has some problem.

```
    def format(tag, time, record)
      [time, record].to_msgpack
    end
```

The type of the 'time' argument is Fluent::EventTime and it contains sub-second field.
But to_msgpack can't handle this correctly, and it seems to be encoded as Fixnum so sub-seconds fields is lost.

**Comment by repeatedly** [comment]
It looks the bug.
With new plugin API, mongo plugin don't need to implement own emit/format.
out_mongo's `format` uses plain `to_msgpack` so it can't handle Fluent::EventTime ext type.
